### ISSUE TITLE
замечания к Т2

### ISSUE THREAD

**Issue by miptkrushitel** [Tokomeir/mat-stat#1]
Некоторые сомнения вызывает ядерная оценка, она не очень согласуется с гистограммой. Последний пункт неверно, элементы вариационного ряда зависимы. Задача Т3 правильно.

**Comment by Tokomeir** [comment]
> Некоторые сомнения вызывает ядерная оценка, она не очень согласуется с гистограммой. Последний пункт неверно, элементы вариационного ряда зависимы. Задача Т3 правильно.

![download](https://user-images.githubusercontent.com/38697168/196184516-5a20f7dd-1257-4305-b1a2-938c0c42a803.png)
![download](https://user-images.githubusercontent.com/38697168/196184642-de9c063d-cfa5-44a4-8b7c-f233ac9f84bc.png)
![download](https://user-images.githubusercontent.com/38697168/196184782-b7feeafd-786c-485c-851a-82811aae256c.png)

Возможно ли, что странность ядерной оценки вызвана не очень удачной выборкой? При других выборках ядерная оценка согласуется с гистограммой, нет?

Исправил пункт f

**Comment by miptkrushitel** [comment]
Да, теперь лучше.
